server.port=8081
app.name=SafeMail Java Backend
jwt.secret=very_long_secret_key_for_local_development_please_change_in_production_1234567890
jwt.expiration-ms=86400000
spring.jackson.default-property-inclusion=non_null
